version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 VidTalk.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: